version: '1.0.0'
configuration:
- Debug
- Release
platform: Any CPU
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "Coremero\Coremero" -c "%CONFIGURATION%" --version-suffix %LABEL%
after_build:
- dotnet pack "Coremero\Coremero" -c %CONFIGURATION% --version-suffix %LABEL% -o ..\..\artifacts
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'
only_commits:
  files:
    - Coremero\Coremero\