version: '1.0.0-CI{build}'
configuration:
- Debug
- Release
platform: Any CPU
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet pack "Coremero\Coremero" -c %CONFIGURATION% --version-suffix "CI{build}" -o ..\..\artifacts
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'
only_commits:
  files:
    - Coremero\Coremero\